### ISSUE TITLE
JSON Schema (Draft 4)

### ISSUE THREAD

**Issue by mrenvoize** [citation-style-language/schema#127]
JSON Schema has hit draft 4 now, but the json schema's here are still following the draft 3 spec.

**Comment by rmzelle** [comment]
Good point. Did you create https://github.com/mrenvoize/schema/commit/f29d6c65d998a33cebdbc824068da15767e4e212 by hand, or is there a draft3-to-draft4 converter?

**Comment by mrenvoize** [comment]
I created it.. just verifying it's all correct then I was going to make a pull request ;)

**Comment by rmzelle** [comment]
Okay, let me know if you come across any issues. When submitting the PR, just modify the existing schema files. I might not be able to accept it right away, since I think Zotero and Mendeley both rely on the current JSON schema for validation, and we should make sure they both can handle draft 4. We'll deal with that once the PR is in good shape, though.

**Comment by rmzelle** [comment]
See http://stackoverflow.com/questions/17205260/json-schema-draft4-vs-json-schema-draft3 and https://github.com/json-schema/json-schema/wiki/ChangeLog, and https://jsonschemalint.com/#/version/draft-04/markup/json.

**Comment by rmzelle** [comment]
(Zotero developer `@adomasven` said that Zotero doesn't use these schema right now: https://forums.zotero.org/discussion/comment/283533/#Comment_283533)

**Comment by mrenvoize** [comment]
I'd be really interested to see these updated.. Both to the latest schema sealy versions and to reflect the data structure zotero now uses as alluded to in that linked thread.  

_Sent from my Sony D5803 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
