### ISSUE TITLE
Correct way to format ISSN in CSL-JSON for a given citation?

### ISSUE THREAD

**Issue by coryschires** [citation-style-language/schema#165]
I understand ISSNs are two sets of four digits separated by a hyphen (e.g. `1234-1234`). [That much is clear](https://en.wikipedia.org/wiki/International_Standard_Serial_Number).

But what is the best way to format this in CSL-JSON for a given citation. Here are some different examples, I have seen in the wild:

* `"ISSN": ["0894-4393", "1552-8286"]`
* `"ISSN": "0894-4393"`
* `"ISSN": "ISSN 0894-4393"`
* `"ISSN": "eISSN 0894-4393"`
* `"ISSN": "pISSN 0894-4393"`

Is there a correct (or at least recommended) way to handle this? Or maybe any of these example are acceptable?

Unfortunately, I couldn't find anything specifically addressing this in the docs. 

Thanks for help!

**Comment by rmzelle** [comment]
@coryschires, you're right that there is no easy answer. In general, I would tend to just pick one of the ISSNs and use that as sole value, e.g. `"ISSN": "0894-4393"`.

It would probably be better to have distinct variables for the different ISSN types that exist (print, electronic, linking), so that CSL styles can address them individually and apply labels as necessary. But right now we just have the generic "ISSN" CSL variable and CSL-JSON field.

**Comment by coryschires** [comment]
Thanks for the clarification! I'll go with something simple like `"ISSN": "0894-4393"`.

Closing!
