### ISSUE TITLE
Retire master branch

### ISSUE THREAD

**Issue by bwiernik** [citation-style-language/schema#378]
@rmzelle suggested a few months back that we retire the `master` branch on the schema and documentation repos and instead just use the `v1.0` and `v1.1` branches. After spending a few months trying to manage the state `v1.0`, `master`, and `v1.1` separately, I've come to agree. Currently, `master` is essentially aligned with `v1.0`. I suggest we retire it at this point.

Then, we would make `v1.0` the default branch for the repository until `v1.1` is released, when we would change the default branch to that.

What do folks think?

**Comment by bdarcus** [comment]
@dhimmel - we've talked a bit about potential changes to our git strategy going forward.

Any thoughts on this proposal?

I'm pretty much agnostic.

I do think the challenges of the past few months are likely to be unique to this time though; that a number of us where making changes, on two different versions, on often the same files.

**Comment by denismaier** [comment]
Also quite agnostic on this.

Three branches is certainly two much. So we could have `master` + `whatever-the-next-version-is`. Or `1.0` and `1.1`, later `1.2.`.
Or just one branch, and feature branches that get merged whenever appropriate? 

> I do think the challenges of the past few months are likely to be unique to this time though; that a number of us where making changes, on two different versions, on often the same files.

Absolutely, not to forget the huge backlog of issues, with some having more impact than others.

**Comment by bdarcus** [comment]
One practical issue I do wonder about, however, is the implications of
regularly, even if infrequently, changing the default branch.

**Comment by dhimmel** [comment]
> One practical issue I do wonder about, however, is the implications of regularly, even if infrequently, changing the default branch.

The main issues I imagine are:

1. pull requests that need to be updated to a new base branch. I think this can be done in the GitHub UI
2. forks, clones, and other remote repos that must keep track of what the latest default branch is, rather than just always tracking master to get the latest.

I haven't fully understood the branches use case for this project.

I think the most common workflow is to create a tag for every release. If you are only doing MAJOR.MINOR, then tags are probably all you need, until perhaps you move to version 2.0 and want to continue incrementing 1.*.

But for this project, I think an entirely linear release order would make sense. For example, 1.0, 1.1, 1.2, 2.0, 2.1... In this case, there is no need for branches at all besides `master` (or whatever you want to name your single default branch).

**Comment by georgd** [comment]
> > One practical issue I do wonder about, however, is the implications of regularly, even if infrequently, changing the default branch.
> 
> The main issues I imagine are:
> 
> 1. pull requests that need to be updated to a new base branch. I think this can be done in the GitHub UI

Agreed.

> 2. forks, clones, and other remote repos that must keep track of what the latest default branch is, rather than just always tracking master to get the latest.

I don’t see this so much as an issue. Regarding the stability of the code, I don’t expect the default branch to change often. CSL is used by many diverse projects which might not catch up with new releases at the same time. The typical downstream project will probably rather stay with one (major) release than always follow the latest development. Therefore, I think it makes sense to impose the burden of paying attention to changing default branches to projects that need to do so rather than to make all the other projects aware of potential breakage when linking to the default branch. A downstream project would link to one version branch and stay on it until it’s ready for the upgrade. And, looking at the current situation, I assume that 1.0 will still be used quite some time after the release of 1.1. Doing the work in multiple branches rather than in one single  will allow for easy bug fixes to legacy branches.

**Comment by denismaier** [comment]
@georgd but can't we just use tags for that? A project will depend on 1.0.2, and that's fine. They can then choose to upgrade to 1.1 whenever that seems appropriate

**Comment by georgd** [comment]
> @georgd but can't we just use tags for that? A project will depend on 1.0.2, and that's fine. They can then choose to upgrade to 1.1 whenever that seems appropriate

It would, but what about bug fixes. I think it’s easier for everybody to do a 1.0.3 bug-fix-release in a 1.0 branch than doing some git wizardry in the single default branch to get it out.

**Comment by bdarcus** [comment]
I was always assuming we'd merge the 1.1 branch to master after some vetting period, and tag 1.1.0 when ready.

We'd then do future development on master, with the exception of (likely rare) bug fixes on the x.x branches.

In short, I don't see why we should retire master.
